import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

// Shell completion drift gate (M113). completions/*.bash / _daimon / *.ps1 are
// committed files generated by scripts/build-completions.mjs from
// src/cliSurface.ts (via dist/cliHelp.js). This suite fails whenever the
// committed files stop matching what the generators produce right now — a
// hand edit, a forgotten regen after a CLI-surface change, or a generator bug
// all show up the same way: byte inequality.

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dist = p => pathToFileURL(path.resolve(repoRoot, 'dist', p)).href;

const { completionBash, completionZsh, completionPowershell } = await import(dist('cliHelp.js'));
const { CLI_SUBCOMMANDS } = await import(dist('cliSurface.js'));

const REGEN_HINT = 'run `npm run build && npm run build:completions` and commit the result';

const FILES = [
  ['daimon.bash', completionBash],
  ['_daimon', completionZsh],
  ['daimon.ps1', completionPowershell],
];

function committedPath(name) {
  return path.join(repoRoot, 'completions', name);
}

function normalized(s) {
  // Mirrors build-completions.mjs's own normalization so a stray CRLF from a
  // Windows checkout can never manufacture false drift.
  return s.replace(/\r\n/g, '\n');
}

test('completions/ drift gate: committed files match the live generators', () => {
  for (const [name, gen] of FILES) {
    const p = committedPath(name);
    assert.ok(fs.existsSync(p), `completions/${name} is missing — ${REGEN_HINT}`);
    const expected = normalized(gen());
    const actual = normalized(fs.readFileSync(p, 'utf8'));
    assert.equal(actual, expected, `completions/${name} has drifted from src/cliSurface.ts — ${REGEN_HINT}`);
  }
});

test('drift detection proof: a mutated scratch copy is caught (committed file untouched)', () => {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'daimon-completion-drift-'));
  try {
    for (const [name, gen] of FILES) {
      const scratchPath = path.join(tmp, name);
      fs.copyFileSync(committedPath(name), scratchPath);
      const expected = normalized(gen());

      // Sanity: an untouched copy of the committed file matches the generator
      // (this is the same comparison the drift gate above performs).
      assert.equal(normalized(fs.readFileSync(scratchPath, 'utf8')), expected, `${name}: scratch fixture should start clean`);

      // Mutate ONLY the scratch copy and confirm the comparison logic flags it.
      fs.appendFileSync(scratchPath, '\n# drift-test mutation — must never match generator output\n');
      const mutated = normalized(fs.readFileSync(scratchPath, 'utf8'));
      assert.notEqual(mutated, expected, `${name}: mutation went undetected — the drift comparison itself is broken`);
    }
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
});

test('spot-check: export/report/ports/mute verbs and the `diff` subword appear in every shell', () => {
  const required = ['export', 'report', 'ports', 'mute', 'diff'];
  for (const [name, gen] of FILES) {
    const text = gen();
    for (const token of required) {
      assert.ok(text.includes(token), `completions for ${name} (via ${gen.name}) are missing "${token}"`);
    }
  }
});

test('sanity: every CLI_SUBCOMMANDS verb (first word) appears in every shell script', () => {
  const firstWords = new Set(CLI_SUBCOMMANDS.map(c => c.name.split(' ')[0]));
  assert.ok(firstWords.size > 0, 'CLI_SUBCOMMANDS should not be empty');
  for (const [name, gen] of FILES) {
    const text = gen();
    for (const word of firstWords) {
      assert.ok(text.includes(word), `completions for ${name} are missing verb "${word}" (CLI_SUBCOMMANDS drifted ahead of the generator)`);
    }
  }
});
