import type { Stability } from './stability.js';

export type CliGroup =
  | 'lifecycle'
  | 'queries'
  | 'agent'
  | 'introspection'
  | 'config'
  | 'claude'
  | 'plugin';

export interface CliOption {
  flag: string;
  arg?: string;
  description: string;
}

export interface CliSubcommand {
  name: string;
  args: string;
  summary: string;
  example: string;
  needsDaemon: boolean;
  group: CliGroup;
  // Stability tier (M87): frozen verbs' JSON output shapes are additive-only
  // forever and each has a golden-shape snapshot in test/fixtures/contract.
  // See STABILITY.md.
  stability: Stability;
  description: string;
  options?: CliOption[];
  examples?: string[];
  exitCodes?: { code: number; meaning: string }[];
  aliases?: string[];
}

export const CLI_GROUPS: { id: CliGroup; title: string }[] = [
  { id: 'lifecycle', title: 'lifecycle' },
  { id: 'queries', title: 'queries' },
  { id: 'agent', title: 'agent verbs' },
  { id: 'introspection', title: 'introspection' },
  { id: 'config', title: 'config' },
  { id: 'claude', title: 'claude' },
  { id: 'plugin', title: 'plugin' },
];

const stdExit = [
  { code: 0, meaning: 'success' },
  { code: 1, meaning: 'error' },
];

const exitWithTimeout = [
  ...stdExit,
  { code: 2, meaning: 'target state not reached within --timeout' },
];

// Emitted by any command that resolves a bare `<name>` when that name matches
// apps in more than one workspace (HTTP 412 name-collision). Callers pass --cwd
// or --workspace to disambiguate. Documented on every name-taking command so an
// agent scripting against exit codes recognises it.
const collisionCode = { code: 4, meaning: 'app name matches multiple workspaces (pass --cwd or --workspace)' };
const lockCode = { code: 5, meaning: 'soft-lock held by another agent (pass --steal to override)' };
const perAppExit = [...stdExit, collisionCode];
const perAppExitWithTimeout = [...exitWithTimeout, collisionCode];

export const CLI_SUBCOMMANDS: CliSubcommand[] = [
  {
    name: 'list',
    args: '[--tag <name>] [--workspace <label>] [--group <group>] [--full|--compact] [--stream] [--explain]',
    summary: 'List apps. Compact by default; --full for v0.4 shape; --stream for NDJSON; --explain wraps with _meta (searchRoots, scanned, rejected, suggestion).',
    description: 'List discovered apps. Compact JSON is the default; pass --full for the v0.4-shape full snapshot. --stream emits NDJSON until SIGINT. --explain wraps the response with _meta describing discovery. --group filters to a named group\'s members (and, being a global working set, skips the cwd scope like --all).',
    example: 'daimon list',
    examples: ['daimon list', 'daimon list --tag web', 'daimon list --group day', 'daimon list --full --workspace fullstack', 'daimon list --stream'],
    options: [
      { flag: '--tag', arg: '<name>', description: 'Filter to apps carrying this tag (repeatable).' },
      { flag: '--workspace', arg: '<label>', description: 'Filter to a workspace label.' },
      { flag: '--group', arg: '<group>', description: 'Filter to a named group\'s members (v1.1, experimental).' },
      { flag: '--full', description: 'Emit the full v0.4-shape snapshot per app.' },
      { flag: '--compact', description: 'Emit compact JSON (default).' },
      { flag: '--stream', description: 'NDJSON stream until SIGINT.' },
      { flag: '--explain', description: 'Wrap with discovery _meta (searchRoots, scanned, rejected, suggestion).' },
    ],
    needsDaemon: true,
    group: 'queries',
    stability: 'frozen',
    aliases: ['ls'],
    exitCodes: stdExit,
  },
  {
    name: 'status',
    args: '<name> [--full|--compact] | --group <group>',
    summary: 'Get the current status of one app (compact by default), or of a whole group with --group.',
    description: 'Show the current status of one app. Compact JSON is the default. With --group <group> (v1.1, experimental) and no app name: per-member compact statuses plus a "3/4 healthy" summary.',
    example: 'daimon status web-admin',
    options: [
      { flag: '--full', description: 'Full v0.4-shape snapshot.' },
      { flag: '--compact', description: 'Compact JSON (default).' },
      { flag: '--group', arg: '<group>', description: 'Statuses for a named group\'s members (v1.1, experimental).' },
    ],
    needsDaemon: true,
    group: 'queries',
    stability: 'frozen',
    aliases: ['ps'],
    exitCodes: perAppExit,
  },
  {
    name: 'errors',
    args: '<name> [--since 2m] [--since-last] [--client <id>] [--structured] [--full|--compact] | --group [<group>]',
    summary: 'Get deduplicated errors for an app. Compact by default ({file,line,col,code,message}). --group (no name) groups all apps\' errors by stack fingerprint.',
    description: 'Deduplicated parsed errors for an app. Compact JSON by default. With --group and no app name, returns all apps\' errors grouped by stack fingerprint (source location or normalized message) with count, first/last-seen and affected apps.',
    example: 'daimon errors web-admin --since 5m',
    options: [
      { flag: '--group', arg: '[<group>]', description: 'Bare: group all apps\' errors by stack fingerprint (omit <name>). With a value (v1.1, experimental): filter to a named group\'s members.' },
      { flag: '--since', arg: '<duration>', description: 'Time window (e.g. 30s, 5m, 1h).' },
      { flag: '--since-last', description: 'Only errors since the previous --since-last call (per --client).' },
      { flag: '--client', arg: '<id>', description: 'Cursor identity for --since-last.' },
      { flag: '--structured', description: 'Emit only parsed {file,line,col,code,message} rows.' },
      { flag: '--full', description: 'Full per-error entries.' },
      { flag: '--compact', description: 'Compact JSON (default).' },
    ],
    needsDaemon: true,
    group: 'queries',
    stability: 'frozen',
    exitCodes: perAppExit,
  },
  {
    name: 'events',
    args: '[--since 1h] [--app <name>] [--stream]',
    summary: 'Get the event log. --stream emits NDJSON until SIGINT.',
    description: 'Get the global event log. --stream emits NDJSON until SIGINT. Filter to a single app with --app.',
    example: 'daimon events --since 1h',
    options: [
      { flag: '--since', arg: '<duration>', description: 'Time window.' },
      { flag: '--app', arg: '<name>', description: 'Filter to a single app.' },
      { flag: '--stream', description: 'NDJSON stream.' },
    ],
    needsDaemon: true,
    group: 'queries',
    stability: 'frozen',
    exitCodes: stdExit,
  },
  {
    name: 'wait',
    args: '<name> [--until serving|healthy|stopped|error] [--timeout 120s]',
    summary: 'Block until app reaches the given state.',
    description: 'Block until an app reaches the given terminal state. Exits 2 on timeout.',
    example: 'daimon wait web-admin --until healthy',
    options: [
      { flag: '--until', arg: '<state>', description: 'Target state (serving|healthy|stopped|error). Default: serving.' },
      { flag: '--timeout', arg: '<duration>', description: 'Max wait, parsed as 120s/5m (default 120s).' },
    ],
    needsDaemon: true,
    group: 'agent',
    stability: 'frozen',
    exitCodes: perAppExitWithTimeout,
  },
  {
    name: 'ensure',
    args: '<name> [--until serving|healthy] [--timeout 180s]',
    summary: 'One-call: start if needed, block to target state, return terminal state. Idempotent.',
    description: 'Idempotent start+wait: starts the app if not already serving, then blocks until --until is reached.',
    example: 'daimon ensure web-admin',
    options: [
      { flag: '--until', arg: '<state>', description: 'Target state (serving|healthy). Default: healthy.' },
      { flag: '--timeout', arg: '<duration>', description: 'Max wait (default 180s).' },
    ],
    needsDaemon: true,
    group: 'agent',
    stability: 'stable',
    exitCodes: exitWithTimeout,
  },
  {
    name: 'ensure-up',
    args: '<profile> [--until serving|healthy] [--timeout 300s]',
    summary: 'One-call: cascade-start every app in the profile and wait for each to reach target.',
    description: 'Cascade-start every app in the profile and wait for each to reach the target state.',
    example: 'daimon ensure-up fullstack',
    options: [
      { flag: '--until', arg: '<state>', description: 'serving|healthy (default: healthy).' },
      { flag: '--timeout', arg: '<duration>', description: 'Global budget (default 300s).' },
    ],
    needsDaemon: true,
    group: 'agent',
    stability: 'stable',
    exitCodes: exitWithTimeout,
  },
  {
    name: 'overview',
    args: '[--workspace <label>] [--profile <name>] [--budget <tokens>]',
    summary: 'Decision-ready snapshot: totals, byStatus, needsAttention (with first parsed error), recentlyChanged. First call in a session. --budget caps the response size for agents; overflow collapses to _meta.omitted.',
    description: 'Decision-ready snapshot — totals, byStatus, needsAttention (with first parsed error), recentlyChanged. Designed as the first call in an agent session.',
    example: 'daimon overview --budget 1500',
    options: [
      { flag: '--workspace', arg: '<label>', description: 'Filter to one workspace label.' },
      { flag: '--profile', arg: '<name>', description: 'Filter to apps in this profile.' },
      { flag: '--budget', arg: '<tokens>', description: 'Cap response size; overflow collapses to _meta.omitted.' },
    ],
    needsDaemon: true,
    group: 'agent',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'focus',
    args: '<name> [--until serving|healthy|stable] [--timeout 180s]',
    summary: 'One round-trip subscribe-then-act: streams NDJSON of status/error/url events for one app until target state or timeout. Designed for agents.',
    description: 'Subscribe-then-act: stream NDJSON of status/error/url events for one app until --until or --timeout.',
    example: 'daimon focus web-admin --until stable',
    options: [
      { flag: '--until', arg: '<state>', description: 'serving|healthy|stable (default: healthy).' },
      { flag: '--timeout', arg: '<duration>', description: 'Max wait (default 180s).' },
    ],
    needsDaemon: true,
    group: 'agent',
    stability: 'stable',
    exitCodes: exitWithTimeout,
  },
  {
    name: 'try-fix',
    args: '<name> [--until serving|healthy] [--timeout 180s]',
    summary: 'Composite: run doctor --auto-fix on permitted rules, restart the app, wait for target, return {before,after,fixed,stillFailing}. Never edits user source.',
    description: 'Run doctor --auto-fix on permitted rules, restart the app, wait for target. Never edits user source.',
    example: 'daimon try-fix web-admin',
    options: [
      { flag: '--until', arg: '<state>', description: 'serving|healthy (default: healthy).' },
      { flag: '--timeout', arg: '<duration>', description: 'Max wait (default 180s).' },
    ],
    needsDaemon: true,
    group: 'agent',
    stability: 'stable',
    exitCodes: exitWithTimeout,
  },
  {
    name: 'orchestrate',
    args: '<profile> [--goal serving|healthy|stable] [--timeout 300s] [--dry-run] [--budget <tokens>]',
    summary: 'Bring up a whole profile in one call: cascade-start, wait for goal, run ONE try-fix round on stragglers. Returns {profile, goal, perApp, totalMs, allReached}. --dry-run reports planned order only. Designed for agents.',
    description: 'Bring up a whole profile in one call: cascade-start, wait, one try-fix round on stragglers.',
    example: 'daimon orchestrate fullstack --goal stable',
    options: [
      { flag: '--goal', arg: '<state>', description: 'serving|healthy|stable (default: healthy).' },
      { flag: '--timeout', arg: '<duration>', description: 'Global budget (default 300s).' },
      { flag: '--dry-run', description: 'Print planned order without executing.' },
      { flag: '--budget', arg: '<tokens>', description: 'Cap response size.' },
    ],
    needsDaemon: true,
    group: 'agent',
    stability: 'stable',
    exitCodes: exitWithTimeout,
  },
  {
    name: 'pin-health',
    args: '<name> [--accept] [--path <p>]',
    summary: 'Show the auto-discovered health-probe path for an app; --accept persists it as overrides.<name>.healthProbePath in daimon.config.json and soft-reloads. Default behaviour is opt-in: nothing is written without --accept.',
    description: 'Show the auto-discovered health-probe path for an app. --accept persists it to daimon.config.json.',
    example: 'daimon pin-health api --accept',
    options: [
      { flag: '--accept', description: 'Persist the candidate path to overrides.<name>.healthProbePath.' },
      { flag: '--path', arg: '<p>', description: 'Override the candidate path explicitly.' },
    ],
    needsDaemon: true,
    group: 'config',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'logs',
    args: '<name> [--tail N] [--since 30s] [--grep <regex>] [--stream] | --group <group>',
    summary: 'Recent log lines for an app. --grep filters server-side (regex, ≤512 chars); --stream follows the live tail as NDJSON; --group merges a group\'s tails.',
    description: 'Recent log lines for an app. --grep applies a case-insensitive regex filter on the daemon (length-capped at 512 chars). --stream follows the live tail (SSE under the hood) and emits NDJSON {ts,line} until SIGINT — combine with --grep for a filtered live tail. With --group <group> (v1.1, experimental) and no app name: a timestamp-merged tail across the group\'s members, each line carrying its app.',
    example: 'daimon logs web-admin --grep "ERROR|ECONNREFUSED" --stream',
    options: [
      { flag: '--tail', arg: '<N>', description: 'Last N lines (default 50).' },
      { flag: '--since', arg: '<duration>', description: 'Time window.' },
      { flag: '--grep', arg: '<regex>', description: 'Server-side case-insensitive regex filter (max 512 chars).' },
      { flag: '--stream', description: 'Follow the live tail; NDJSON until SIGINT.' },
      { flag: '--group', arg: '<group>', description: 'Merged tail across a named group\'s members (v1.1, experimental).' },
    ],
    needsDaemon: true,
    group: 'queries',
    stability: 'frozen',
    aliases: ['log'],
    exitCodes: perAppExit,
  },
  {
    name: 'start',
    args: '<name> [--with-deps] [--steal]',
    summary: 'Start an app. --steal overrides another agent\'s soft-lock.',
    description: 'Start an app. If another agent holds the soft-lock, this exits 5 unless --steal is passed.',
    example: 'daimon start web-admin',
    options: [
      { flag: '--with-deps', description: 'Also start declared dependencies.' },
      { flag: '--steal', description: 'Override another agent\'s soft-lock.' },
    ],
    needsDaemon: true,
    group: 'lifecycle',
    stability: 'frozen',
    exitCodes: [...perAppExit, lockCode],
  },
  {
    name: 'stop',
    args: '<name> [--steal]',
    summary: 'Stop an app. --steal overrides another agent\'s soft-lock. A name matching no app but a group stops the group (app-name precedence).',
    description: 'Stop an app. If another agent holds the soft-lock, this exits 5 unless --steal is passed. App-name precedence is absolute: an existing app of the name behaves exactly as always; only when no app matches and a v1.1 group of that name exists do the group\'s members stop, in reverse depends order.',
    example: 'daimon stop web-admin',
    options: [
      { flag: '--steal', description: 'Override another agent\'s soft-lock.' },
    ],
    needsDaemon: true,
    group: 'lifecycle',
    stability: 'frozen',
    exitCodes: [...perAppExit, lockCode],
  },
  {
    name: 'restart',
    args: '<name> [--steal]',
    summary: 'Restart an app. --steal overrides another agent\'s soft-lock.',
    description: 'Restart an app. If another agent holds the soft-lock, this exits 5 unless --steal is passed.',
    example: 'daimon restart web-admin',
    options: [
      { flag: '--steal', description: 'Override another agent\'s soft-lock (default: refuse with exit 5).' },
    ],
    needsDaemon: true,
    group: 'lifecycle',
    stability: 'frozen',
    exitCodes: [...perAppExit, lockCode],
  },
  {
    name: 'test',
    args: '<name> [--timeout <dur>] [--steal] [--json]',
    summary: 'Run the app\'s own test suite once: resolves the runner (vitest/jest/pytest/go/cargo/dotnet or overrides.<app>.testCommand), parses failures with file:line, records the run in history. Exit 0 all pass, 1 failures, 2 timeout.',
    description: 'Run the project\'s own test runner once and parse the result. Runner resolution: overrides.<app>.testCommand wins; otherwise the app\'s framework profile hints the runner (JS profiles pick vitest vs jest by dependency check). Failures come back as {suite,test,file,line,message}; the run lands in test_runs/test_failures and GET /api/tests. Takes the per-app soft lock — a second agent\'s concurrent test gets exit 5 unless --steal. daimon never installs or replaces a runner.',
    example: 'daimon test web-admin',
    options: [
      { flag: '--timeout', arg: '<duration>', description: 'Max suite runtime (default 300s, max 600s). Expiry tree-kills the runner and exits 2.' },
      { flag: '--steal', description: 'Override another agent\'s soft-lock.' },
      { flag: '--json', description: 'Structured JSON (default output is already JSON; kept for symmetry).' },
    ],
    needsDaemon: true,
    group: 'lifecycle',
    stability: 'stable',
    exitCodes: [...exitWithTimeout, collisionCode, lockCode],
  },
  {
    name: 'context',
    args: '<name> [--budget <chars>]',
    summary: 'Agent context pack: status/framework/uptime, top error groups, last crash, last test run, compile stats, suspect commits, locks — one call instead of six.',
    description: 'Assemble the full debugging picture for an app in one round-trip: compact status (+framework, workspaceRoot), top 5 error fingerprint groups (24h), last crash report, last test run with failures, compile p50/p95 + last regression, suspect commits, and active locks/agents. --budget <chars> drops sections lowest-priority-first (compile → agents → crashes → tests → errors; status never drops) and lists them in truncated[]. Composition only — no new state.',
    example: 'daimon context web-admin --budget 4000',
    options: [
      { flag: '--budget', arg: '<chars>', description: 'Character cap; overflow sections drop lowest-priority-first into truncated[].' },
    ],
    needsDaemon: true,
    group: 'agent',
    stability: 'stable',
    exitCodes: perAppExit,
  },
  {
    name: 'search',
    args: '<query> [--app <a>] [--since <dur>] [--kind logs|errors|events] [--limit N]',
    summary: 'Full-text search over everything daimon has seen: log lines, errors, and events. Compact JSON hits {kind,app,ts,snippet,ref}.',
    description: 'FTS5 search across the history DB — per-app log lines (indexed by default; opt out with search.logIndex or overrides.<app>.logIndex), plus all errors and events. A trailing * on a term does prefix search. Degrades to a LIKE scan (fallback:true) if FTS is unavailable.',
    example: 'daimon search "ECONNREFUSED" --app api --since 24h',
    options: [
      { flag: '--app', arg: '<name>', description: 'Restrict to one app.' },
      { flag: '--since', arg: '<duration>', description: 'Time window (e.g. 30m, 24h, 7d).' },
      { flag: '--kind', arg: '<k>', description: 'logs|errors|events (default: all).' },
      { flag: '--limit', arg: '<N>', description: 'Max hits (default 50, max 500).' },
    ],
    needsDaemon: true,
    group: 'queries',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'test-history',
    args: '<name> [--flaky] [--limit N]',
    summary: 'Recent test runs for an app (totals, exit codes, gitHead, failures). --flaky lists tests that flipped pass↔fail ≥3× at the same gitHead.',
    description: 'Compact JSON of recent test runs recorded by `daimon test`. With --flaky, returns the flaky-test list (fingerprint, test, flips, gitHead) derived from run history at each gitHead.',
    example: 'daimon test-history web-admin --flaky',
    options: [
      { flag: '--flaky', description: 'List flaky tests instead of runs.' },
      { flag: '--limit', arg: '<N>', description: 'Max runs to return (default 20).' },
    ],
    needsDaemon: true,
    group: 'queries',
    stability: 'stable',
    exitCodes: perAppExit,
  },
  {
    name: 'agents',
    args: '',
    summary: 'List active agents touching this daemon and any current per-app soft-locks.',
    description: 'Print active agents (id, lastSeen, cwd, callCount) and any per-app soft-locks. Each agent gets a stable per-session id sent on every request; the same id is recorded in the audit log\'s 6th column.',
    example: 'daimon agents',
    needsDaemon: true,
    group: 'agent',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'handoff',
    args: '<app> <agentId>',
    summary: 'Transfer the soft-lock on <app> to another agent.',
    description: 'Transfer the per-app soft-lock from this agent (or any holder) to <agentId>. Useful to tell another agent "I\'m done — you can take this".',
    example: 'daimon handoff web-admin claude-host-1234-abcd',
    needsDaemon: true,
    group: 'agent',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'profiles suggest',
    // The CLI dispatches on the first token (`profiles`), so alias it to this
    // entry — otherwise findSubcommand('profiles') misses and the verb neither
    // auto-spawns the daemon nor resolves `daimon help profiles`.
    aliases: ['profiles'],
    args: '[--since 30d] [--min 5]',
    summary: 'Suggest profile candidates from recurring co-starts.',
    description: 'Scan recent status events for app sets the user repeatedly starts together within a short window. Returns suggested profiles with name, apps, cooccurrence count, and last-seen time. Skips clusters that already match an existing profile.',
    example: 'daimon profiles suggest --since 30d --min 5',
    needsDaemon: true,
    group: 'agent',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'up',
    args: '[<group>|<profile>] [--until serving|healthy] [--timeout 300s] [--steal]',
    summary: 'Start a group or profile (or autoStart). Groups resolve first: depends-aware topo order + a "3/4 healthy" readiness summary. Profiles behave as before.',
    description: 'Start a named group or legacy profile (no argument = the autoStart list). Groups (v1.1) resolve first: the daemon starts members and their depends closure in topological order, waits per level, and returns a per-app readiness summary with a "3/4 healthy" tail (exit 2 when not all reached). Legacy profile invocations behave exactly as before. --until/--timeout/--steal apply to the group path.',
    example: 'daimon up day',
    examples: ['daimon up day', 'daimon up fullstack', 'daimon up'],
    options: [
      { flag: '--until', arg: '<state>', description: 'Group target: serving|healthy (default healthy; groups only).' },
      { flag: '--timeout', arg: '<duration>', description: 'Group global budget (default 300s; groups only).' },
      { flag: '--steal', description: 'Override other agents\' soft-locks on group members.' },
    ],
    needsDaemon: true,
    group: 'lifecycle',
    stability: 'stable',
    exitCodes: exitWithTimeout,
  },
  {
    name: 'down',
    args: '[<group>|<profile>]',
    summary: 'Stop a group, a profile, or all apps. Groups resolve first and stop members in reverse depends order.',
    description: 'Stop a named group or legacy profile (no argument = all apps). Groups (v1.1) resolve first: members stop in reverse depends order — dependents before dependencies; external dependencies are never stopped implicitly. Legacy profile invocations behave exactly as before.',
    example: 'daimon down',
    examples: ['daimon down', 'daimon down day'],
    options: [
      { flag: '--steal', description: 'Override other agents\' soft-locks on group members (groups only).' },
    ],
    needsDaemon: true,
    group: 'lifecycle',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'history',
    args: '<name>',
    summary: 'Summary metrics (uptime%, restarts, compile p50/p95, top errors).',
    description: 'Summary metrics for an app (uptime%, restarts, compile p50/p95, top errors).',
    example: 'daimon history web-admin',
    needsDaemon: true,
    group: 'queries',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'mute',
    args: '<name> [--for <dur>]',
    summary: 'Mute OS notifications for an app (optionally for a duration). Persisted; shown in status and the dashboard.',
    description: 'Silence OS notifications for one app. --for takes a duration (30m, 2h, 1d); without it the mute holds until `daimon unmute`. Events, webhooks, and history are unaffected — only desktop notifications stop. Mutes persist across daemon restarts and surface as `muted` in `daimon status` and on the dashboard app card.',
    example: 'daimon mute web-admin --for 2h',
    options: [
      { flag: '--for <dur>', description: 'Auto-expire the mute after this duration (30m, 2h, 1d).' },
    ],
    needsDaemon: true,
    group: 'lifecycle',
    stability: 'experimental',
    exitCodes: perAppExit,
  },
  {
    name: 'unmute',
    args: '<name>',
    summary: 'Lift a notification mute.',
    description: 'Re-enable OS notifications for an app muted with `daimon mute`.',
    example: 'daimon unmute web-admin',
    needsDaemon: true,
    group: 'lifecycle',
    stability: 'experimental',
    exitCodes: perAppExit,
  },
  {
    name: 'report',
    args: '[--since 24h|7d] [--app <a>] [--workspace <label>] [--md]',
    summary: 'The digest: per-app uptime, errors (new/recurring/resolved), test pass-rate + flakiest, compile p50/p95 + regressions, crashes/storms, agent activity, env changes.',
    description: 'Answer "what happened?" over a window (default 24h). Composes existing history — uptime %, error groups classified new/recurring/resolved, test pass rate and flakiest tests, compile p50/p95 with the slowest build and regressions, crashes and restart storms, agent activity, and env-file changes (key names only). Sections with no data degrade to a note, never an error. --md renders human-first markdown suitable for Slack/PRs; JSON stays the default.',
    example: 'daimon report --since 7d --md',
    options: [
      { flag: '--since <window>', description: 'Report window: 24h, 7d, or a duration (default 24h).' },
      { flag: '--app <name>', description: 'Limit to one app.' },
      { flag: '--workspace <label>', description: 'Limit to one workspace label.' },
      { flag: '--group <group>', description: 'Limit to a named group\'s members; the group is named in the header (v1.1, experimental).' },
      { flag: '--md', description: 'Render markdown instead of JSON.' },
    ],
    needsDaemon: true,
    group: 'introspection',
    stability: 'experimental',
    exitCodes: stdExit,
  },
  {
    name: 'env',
    args: '<name> [--use <file>] | diff <name> [--from <ts>] [--to <ts>]',
    summary: 'Env-file awareness: convention files (found/missing), key names, snapshot age; `env diff` shows files/keys added/removed/changed between spawns. --use sets the active env file (pre-v0.13 behavior). Values are NEVER shown.',
    description: 'Read-only env-file awareness (M82). `daimon env <name>` lists the app\'s convention env files (from the framework registry, or envFiles.<app> config), which exist on disk, the key names in the latest spawn snapshot, and its age. `daimon env diff <name>` compares the last two spawn snapshots (or --from/--to ms timestamps): files added/removed, keys added/removed/changed via per-key salted hashes. Raw values are parsed and discarded at snapshot time — they are never stored and never shown; open the file itself.',
    example: 'daimon env web-admin',
    options: [
      { flag: '--from <ts>', description: 'Baseline snapshot at-or-before this ms timestamp (diff).' },
      { flag: '--to <ts>', description: 'Target snapshot at-or-before this ms timestamp (diff).' },
      { flag: '--use', arg: '<file>', description: 'Activate an env file for the app (legacy injection behavior).' },
    ],
    needsDaemon: true,
    group: 'introspection',
    stability: 'experimental',
    exitCodes: perAppExit,
  },
  {
    name: 'why',
    args: '<name>',
    summary: 'One-shot forensics: status, last crash (exit code + final log lines), grouped 24h errors, regressions, restart-storm state, suspect commit, matching doctor findings.',
    description: 'Answer "why is this app broken?" in one call. Composes current status/health, the last crash report (exit code, signal, uptime, last 50 log lines, gitHead), fingerprint-grouped errors from the last 24h, recent regression events, active restart-storm state, the suspect commit at the workspace root, and doctor findings that mention the app. Compact JSON when piped; a readable panel on a TTY.',
    example: 'daimon why web-admin',
    needsDaemon: true,
    group: 'introspection',
    stability: 'stable',
    exitCodes: perAppExit,
  },
  {
    name: 'why-empty',
    args: '',
    summary: 'Explain why `daimon list` is empty: configured searchRoots, scanned/rejected counts, suggested next step.',
    description: 'Explain why `daimon list` is empty — search roots, scanned/rejected counts, suggestion.',
    example: 'daimon why-empty',
    needsDaemon: true,
    group: 'introspection',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'discover',
    args: '',
    summary: 'Run discovery read-only. Prints _meta: searchRoots, scanned, rejected per folder, suggestion.',
    description: 'Run discovery read-only (it never persists). Emits per-folder scanned/rejected and suggestion.',
    example: 'daimon discover',
    needsDaemon: true,
    group: 'introspection',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'frameworks',
    args: '',
    summary: 'List framework profiles (built-in + custom): detection markers, command, which apps matched, rejection stats.',
    description: 'List the framework adapter registry — built-in profiles plus custom profiles from daimon.config.json `frameworks: []`. Shows per-profile match counts, the apps each profile discovered, and discovery rejection stats.',
    example: 'daimon frameworks',
    needsDaemon: true,
    group: 'introspection',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'config validate',
    // Dispatches on the first token, same pattern as `profiles suggest`.
    aliases: ['config'],
    args: '[<path>]',
    summary: 'Validate a daimon config against the known-key schema: unknown keys warn with the nearest valid name; malformed values listed; group checks (unknown apps, autoStart overlap, profile collisions). Exit 0 with warnings, 1 on errors.',
    description: 'Validate daimon.config.json (or an explicit <path>) without starting anything. Unknown top-level keys warn with the nearest valid key name; malformed values report the same field-level warnings the daemon applies at load (falling back to defaults). Groups are checked too: unknown app names (with a nearest-name suggestion), apps in several autoStart sources ("starts once"), and group/profile name collisions ("group wins"). Errors (missing file, invalid JSON) exit 1; warnings alone exit 0 — old configs always stay loadable.',
    example: 'daimon config validate',
    examples: ['daimon config validate', 'daimon config validate ./daimon.config.json'],
    needsDaemon: false,
    group: 'config',
    stability: 'experimental',
    exitCodes: [
      { code: 0, meaning: 'config loads (possibly with warnings)' },
      { code: 1, meaning: 'config unusable (missing file or invalid JSON)' },
    ],
  },
  {
    name: 'export-config',
    args: '[--redacted]',
    summary: 'Emit the active config to stdout. --redacted replaces apiToken with "<redacted>" and rewrites home paths to ~/...',
    description: 'Emit the active config to stdout. --redacted replaces apiToken with "<redacted>" and home paths with ~/...',
    example: 'daimon export-config --redacted',
    options: [
      { flag: '--redacted', description: 'Replace apiToken and home paths.' },
    ],
    needsDaemon: false,
    group: 'config',
    stability: 'frozen',
    exitCodes: stdExit,
  },
  {
    name: 'tasks',
    args: '<name>',
    summary: 'List discovered non-serve tasks.',
    description: 'List discovered non-serve tasks for an app.',
    example: 'daimon tasks web-admin',
    needsDaemon: true,
    group: 'introspection',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'run',
    args: '<name> <task> [--watch] [-- args...]',
    summary: 'Run a discovered task.',
    description: 'Run a discovered task. Pass extra args after `--`.',
    example: 'daimon run web-admin test',
    options: [
      { flag: '--watch', description: 'Keep running and stream output.' },
    ],
    needsDaemon: true,
    group: 'lifecycle',
    stability: 'stable',
    exitCodes: perAppExit,
  },
  {
    name: 'snapshot',
    args: '<name>',
    summary: 'Write a snapshot of app state to ~/.daimon/snapshots.',
    description: 'Write a diagnostic snapshot of app state to ~/.daimon/snapshots.',
    example: 'daimon snapshot web-admin',
    needsDaemon: true,
    group: 'introspection',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'clean',
    args: '<name> [--deep] [--yes]',
    summary: 'Remove build artifacts for an app.',
    description: 'Remove build artifacts for an app. --deep also removes node_modules; --yes skips the confirmation prompt.',
    example: 'daimon clean web-admin --yes',
    options: [
      { flag: '--deep', description: 'Also remove node_modules / language-specific deps caches.' },
      { flag: '--yes', description: 'Skip confirmation prompt.' },
    ],
    needsDaemon: true,
    group: 'lifecycle',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'record',
    args: '',
    summary: 'Toggle session recording.',
    description: 'Toggle JSONL session recording (~/.daimon/sessions).',
    example: 'daimon record',
    needsDaemon: true,
    group: 'introspection',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'replay',
    args: '<session.jsonl> [--speed N]',
    summary: 'Replay a recorded session.',
    description: 'Replay a recorded session.',
    example: 'daimon replay session.jsonl',
    options: [
      { flag: '--speed', arg: '<N>', description: 'Speed multiplier (default 1).' },
    ],
    needsDaemon: true,
    group: 'introspection',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'doctor',
    args: '[--auto-fix] [--dry-run] [--self]',
    summary: 'Sanity-check config + env. --auto-fix repairs orphan daemon, stale lock, missing search root, corrupt history db. --self checks daimon\'s own metrics.',
    description: 'Sanity-check config + env. --auto-fix repairs known issues; --dry-run shows what would change. --self runs the self-observability checks (heap, event-loop lag, history.db query p95).',
    example: 'daimon doctor --auto-fix',
    options: [
      { flag: '--auto-fix', description: 'Apply permitted repairs.' },
      { flag: '--dry-run', description: 'Report planned changes without writing.' },
      { flag: '--self', description: 'Run self-observability checks against the running daemon.' },
    ],
    needsDaemon: false,
    group: 'introspection',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'ports',
    args: '',
    summary: 'Port map: app → port → source (pinned|pool|announced) → pid, plus foreign holders of pool/pinned ports.',
    description: 'Show every app\'s port, how it got it (pinned override, pool auto-assignment, or announced by the app itself), and the owning pid. Also lists foreign processes holding ports in the configured pool or pinned set. Configure auto-assignment with ports.pool ("4200-4299") — only frameworks whose registry row declares portFlag/portEnv participate (M81).',
    example: 'daimon ports',
    needsDaemon: true,
    group: 'introspection',
    stability: 'experimental',
    exitCodes: stdExit,
  },
  {
    name: 'free-port',
    args: '<port> [--force]',
    summary: 'Diagnose / free a port.',
    description: 'Show which process is holding a port. --force kills it.',
    example: 'daimon free-port 4200 --force',
    options: [
      { flag: '--force', description: 'Kill the holder.' },
    ],
    needsDaemon: false,
    group: 'introspection',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'daemon',
    args: 'start|stop|status|restart|attach|install-service [--detach] [--headless]',
    summary: 'Manage the daimon daemon.',
    description: 'Manage the daimon daemon lifecycle.',
    example: 'daimon daemon status',
    options: [
      { flag: '--detach', description: 'Spawn detached (for `start`).' },
      { flag: '--headless', description: 'Start without the TUI (for `start`).' },
    ],
    needsDaemon: false,
    group: 'lifecycle',
    stability: 'frozen',
    exitCodes: stdExit,
  },
  {
    name: 'claude',
    args: 'install|update|uninstall|status [--skill] [--commands] [--agent] [--all] [--dir <path>] [--yes]',
    summary: 'Install/update Claude Code integration artifacts.',
    description: 'Install/update/uninstall the Claude Code integration artifacts.',
    example: 'daimon claude install --all',
    needsDaemon: false,
    group: 'claude',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'init',
    args: '[--force] [--auto]',
    summary: 'Create a daimon config in cwd; --auto picks safe defaults (no prompts) for workspaces with nx/angular/vite markers.',
    description: 'Create a daimon config in cwd. --auto picks safe defaults for known workspace markers.',
    example: 'daimon init --auto',
    options: [
      { flag: '--force', description: 'Overwrite an existing daimon.config.json.' },
      { flag: '--auto', description: 'Skip prompts; pick safe defaults.' },
    ],
    needsDaemon: false,
    group: 'config',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'completion',
    args: '<bash|zsh|fish|powershell>',
    summary: 'Emit a shell completion script for the given shell.',
    description: 'Emit a shell-completion script for bash, zsh, fish, or PowerShell. Pipe the output to the appropriate per-shell location (see README).',
    example: 'daimon completion bash > /etc/bash_completion.d/daimon',
    needsDaemon: false,
    group: 'config',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'plugin',
    args: 'list|show <name>|validate <path>',
    summary: 'Manage doctor plug-ins.',
    description: 'Manage doctor plug-ins. `list` shows installed plug-ins with status; `show <name>` prints a plug-in manifest; `validate <path>` sanity-checks a plug-in file.',
    example: 'daimon plugin list',
    needsDaemon: true,
    group: 'plugin',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'self',
    args: '',
    summary: 'Print daimon\'s own runtime metrics (pid, version, uptime, rss, heap, event-loop lag, history-db p95).',
    description: 'Print daimon\'s own runtime metrics. Useful for bug reports.',
    example: 'daimon self',
    needsDaemon: true,
    group: 'introspection',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'workspaces',
    args: 'list|add [path] [--label <name>] | rm <path> | show [path]',
    summary: 'Manage the workspace registry (searchRoots).',
    description: 'List, add, remove, and inspect workspaces. `add` ensures the given path (defaults to cwd) is a registered searchRoot. `show` reports which workspace covers a cwd.',
    example: 'daimon workspaces list',
    needsDaemon: true,
    group: 'config',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'dashboard',
    args: '',
    summary: 'Open the dashboard in your default browser, scoped to the current cwd.',
    description: 'Open http://127.0.0.1:4999/?cwd=<process.cwd()> in the default browser. The dashboard pre-selects the workspace pill covering cwd.',
    example: 'daimon dashboard',
    needsDaemon: true,
    group: 'introspection',
    stability: 'stable',
    exitCodes: stdExit,
  },
  {
    name: 'ci',
    args: 'start <profile> [--until ready|healthy] [--timeout 5m] [--json]',
    summary: 'CI helper: start a profile and block until all apps are healthy. Designed for GitHub Actions / Jenkins steps.',
    description: 'Start a profile in CI mode and block until each app reaches the target state. Exit 0 on full success, 2 on timeout, 1 on other failure. With --json (default for ci), emits a structured report on stdout: { profile, until, allReached, perApp:[{name, state, reachedTargetMs, timedOut}], totalMs }.',
    example: 'daimon ci start fullstack --until ready --timeout 5m --json',
    options: [
      { flag: '--until', arg: '<state>', description: 'serving|healthy|ready (alias for healthy). Default: healthy.' },
      { flag: '--timeout', arg: '<duration>', description: 'Total budget (default 5m, max 20m).' },
      { flag: '--json', description: 'Force structured JSON report (default for ci).' },
    ],
    needsDaemon: true,
    group: 'agent',
    stability: 'stable',
    exitCodes: exitWithTimeout,
  },
  {
    name: 'timeline',
    args: '[--since 7d] [--app <name>] [--kinds status,error,warning,lint,bundle,task]',
    summary: 'Print a unified chronological event timeline.',
    description: 'Merge status / error / warning / lint / bundle / task / health rows into one chronological stream. JSON output suits piping; use `daimon dashboard` then /timeline for the visual view.',
    example: 'daimon timeline --since 24h --kinds status,error',
    needsDaemon: true,
    group: 'introspection',
    stability: 'stable',
    exitCodes: stdExit,
  },
];

export const CLI_ALIASES: Record<string, string> = {};
for (const c of CLI_SUBCOMMANDS) {
  for (const a of c.aliases ?? []) CLI_ALIASES[a] = c.name;
}

export function findSubcommand(name: string): CliSubcommand | undefined {
  const canonical = CLI_ALIASES[name] ?? name;
  return CLI_SUBCOMMANDS.find(c => c.name === canonical);
}

export function commandsTable(): string {
  const w = Math.max(...CLI_SUBCOMMANDS.map(c => c.name.length));
  return CLI_SUBCOMMANDS.map(c => `${c.name.padEnd(w)}  ${c.summary}`).join('\n');
}

export function usageString(): string {
  return 'usage: daimon <' + CLI_SUBCOMMANDS.map(c => c.name).join('|') + '>';
}
