import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { daimonDir } from './daemon.js';

export interface ServiceArtifact {
  platform: NodeJS.Platform;
  path: string;
  installCmd: string;
  body: string;
}

function nodeExe(): string {
  return process.execPath;
}

function mainJsPath(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.join(here, 'main.js');
}

export function buildServiceArtifact(): ServiceArtifact {
  const platform = process.platform;
  if (platform === 'win32') {
    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- generated by daimon daemon install-service -->
<service>
  <id>daimon</id>
  <name>daimon daemon</name>
  <description>Local Angular/Nx/Vite dev server manager (daimon headless daemon)</description>
  <executable>${nodeExe()}</executable>
  <arguments>"${mainJsPath()}" --headless</arguments>
  <log mode="rotate"/>
  <onfailure action="restart" delay="10 sec"/>
</service>
`;
    const outPath = path.join(daimonDir(), 'daimon-daemon.xml');
    return {
      platform,
      path: outPath,
      body: xml,
      installCmd: `nssm install daimon "${nodeExe()}" "${mainJsPath()}" --headless`,
    };
  }
  if (platform === 'darwin') {
    const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>dev.daimon</string>
  <key>ProgramArguments</key>
  <array>
    <string>${nodeExe()}</string>
    <string>${mainJsPath()}</string>
    <string>--headless</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>${path.join(daimonDir(), 'service.out.log')}</string>
  <key>StandardErrorPath</key><string>${path.join(daimonDir(), 'service.err.log')}</string>
</dict>
</plist>
`;
    const outPath = path.join(os.homedir(), 'Library', 'LaunchAgents', 'dev.daimon.plist');
    return {
      platform,
      path: outPath,
      body: plist,
      installCmd: `launchctl load ${outPath}`,
    };
  }
  const unit = `[Unit]
Description=daimon daemon (local dev-server manager)
After=network.target

[Service]
ExecStart=${nodeExe()} ${mainJsPath()} --headless
Restart=on-failure
RestartSec=10

[Install]
WantedBy=default.target
`;
  const outPath = path.join(os.homedir(), '.config', 'systemd', 'user', 'daimon.service');
  return {
    platform,
    path: outPath,
    body: unit,
    installCmd: `systemctl --user enable daimon && systemctl --user start daimon`,
  };
}

export function installServiceArtifact(): { path: string; installCmd: string; platform: NodeJS.Platform } {
  const a = buildServiceArtifact();
  fs.mkdirSync(path.dirname(a.path), { recursive: true });
  fs.writeFileSync(a.path, a.body, 'utf8');
  return { path: a.path, installCmd: a.installCmd, platform: a.platform };
}
